[build]
  cmd        = "go build -o ./tmp/loyalty-service ./cmd/api"
  bin        = "./tmp/loyalty-service"
  full_bin   = "./tmp/loyalty-service"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "legacy-code"]
  delay      = 1000
  kill_delay = 200

[log]
  time = true

[color]
  main    = "magenta"
  watcher = "cyan"
  build   = "yellow"
  runner  = "green"

[misc]
  clean_on_exit = true
